### ISSUE TITLE
JAVA_HOME is missing

### ISSUE THREAD

**Issue by dominicmarmionswrve** [CircleCI-Public/android-image-preview-docs#10]
Can you set an environment variable for JAVA_HOME?

By running the job with SSH the following commands return blank
`echo $JAVA_HOME`
`which java`

And `java -v` returns `-bash: java: command not found`

**Comment by felicianotech** [comment]
I'll check in on this.

**Comment by Sergio-Mira** [comment]
The output of:
`update-alternatives --list javac`

is:
`/usr/lib/jvm/java-11-openjdk-amd64/bin/javac`
`/usr/lib/jvm/java-8-openjdk-amd64/bin/javac`

**Comment by lokst** [comment]
We are working on setting the `JAVA_HOME` environment variable in the image.

In the meantime, you can include this step in your config.yml, to set `JAVA_HOME`, as a workaround

For Java 11
```
- run:
     name: Set JAVA_HOME
     command: |
       echo 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64' >> $BASH_ENV
```

For Java 8

```
- run:
     name: Set JAVA_HOME
     command: |
       echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' >> $BASH_ENV
```


`which java` and `java --version` should already be working; here's an example of running them in an SSH session

```
circleci@default-377cae22-93fa-4575-9017-0231a432b9d4:~$ which java
/usr/bin/java
circleci@default-377cae22-93fa-4575-9017-0231a432b9d4:~$ java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```
